//App Actions
export const FETCH_PSYCHOLOGISTS = "GET_PSYCHOLOGISTS";
export const PSYCHOLOGISTS_FETCHED = "PSYCHOLOGISTS_FETCHED";

//Psikolog Actions
export const REGISTER_PSYCHOLOGIST = "REGISTER_PSYCHOLOGIST";
export const LOGIN_PSYCHOLOGIST = "LOGIN_PSYCHOLOGIST";
export const PSYCHOLOGIST_REGISTERED = "PSYCHOLOGIST_REGISTERED";
export const PSYCHOLOGIST_LOGGEDIN = "PATIENT_LOGGEDIN";
export const PSYCHOLOGIST_REGISTER_ERROR = "PSYCHOLOGIST_REGISTER_ERROR";
export const PSYCHOLOGIST_LOGIN_ERROR = "PSYCHOLOGIST_LOGIN_ERROR";

//Hasta Actions
export const REGISTER_PATIENT = "REGISTER_PATIENT";
export const LOGIN_PATIENT = "LOGIN_PATIENT";
export const PATIENT_REGISTERED = "PATIENT_REGISTERED";
export const PATIENT_LOGGEDIN = "PATIENT_LOGGEDIN";
export const PATIENT_REGISTER_ERROR = "PATIENT_REGISTER_ERROR";
export const PATIENT_LOGIN_ERROR = "PATIENT_LOGIN_ERROR";


//İşlem Sonuç Actions
export const ERROR_EVENT = "ERROR_EVENT";