//App Actions
export const FETCH_PSYCHOLOGISTS = "FETCH_PSYCHOLOGISTS";
export const PSYCHOLOGISTS_FETCHED = "PSYCHOLOGISTS_FETCHED";
export const FETCH_PSYCHOLOGIST = "FETCH_PSYCHOLOGIST";
export const PSYCHOLOGIST_FETCHED = "PSYCHOLOGIST_FETCHED";
export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS";
export const APPOINTMENTS_FETCHED = "APPOINTMENTS_FETCHED";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const COMMENTS_FETCHED = "COMMENTS_FETCHED";
export const FETCH_BLOG_POST = "FETCH_BLOG_POST";
export const BLOG_POST_FETCHED = "BLOG_POST_FETCHED";
export const FETCH_BLOG_POSTS = "FETCH_BLOG_POSTS";
export const BLOG_POSTS_FETCHED = "BLOG_POSTS_FETCHED";

//Psikolog Actions
export const REGISTER_PSYCHOLOGIST = "REGISTER_PSYCHOLOGIST";
export const LOGIN_PSYCHOLOGIST = "LOGIN_PSYCHOLOGIST";
export const PSYCHOLOGIST_REGISTERED = "PSYCHOLOGIST_REGISTERED";
export const PSYCHOLOGIST_LOGGEDIN = "PATIENT_LOGGEDIN";
export const PSYCHOLOGIST_REGISTER_ERROR = "PSYCHOLOGIST_REGISTER_ERROR";
export const PSYCHOLOGIST_LOGIN_ERROR = "PSYCHOLOGIST_LOGIN_ERROR";
export const APPROVE_APPOINTMENT = "APPROVE_APPOINTMENT";
export const APPOINTMENT_APPROVED = "APPOINTMENT_APPROVED";
export const DECLINE_APPOINTMENT = "DECLINE_APPOINTMENT";
export const APPOINTMENT_DECLINED = "APPOINTMENT_DECLINED";
export const CREATE_BLOG_POST = "CREATE_BLOG_POST";
export const BLOG_POST_CREATED = "BLOG_POST_CREATED";

//Hasta Actions
export const REGISTER_PATIENT = "REGISTER_PATIENT";
export const LOGIN_PATIENT = "LOGIN_PATIENT";
export const PATIENT_REGISTERED = "PATIENT_REGISTERED";
export const PATIENT_LOGGEDIN = "PATIENT_LOGGEDIN";
export const PATIENT_REGISTER_ERROR = "PATIENT_REGISTER_ERROR";
export const PATIENT_LOGIN_ERROR = "PATIENT_LOGIN_ERROR";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const APPOINTMENT_CREATED = "APPOINTMENT_CREATED";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const APPOINTMENT_DELETED = "APPOINTMENT_DELETED";
export const ADD_COMMENT = "ADD_COMMENT";
export const COMMENT_ADDED = "COMMENT_ADDED";


//İşlem Sonuç Actions
export const ERROR_EVENT = "ERROR_EVENT";